export const CITIES = [
  'Bengaluru',
  'NCR',
  'Hyderabad',
  'Chandigarh',
  'Panchkula',
  'Mohali',
  'Mumbai',
  'Pune',
  'Chennai',
  'Coimbatore',
  'Jaipur',
  'Cochin',
  'Vijayawada',
  'Visakhapatnam',
  'Kolkata',
  'Lucknow',
  'Kanpur',
  'Nagpur',
];

export const CATEGORIES = [
  {
    id: Date.now(),
    imageLink: '../../../assets/images/fish-thumbnail.png',
    imageAlt: 'Fish',
    imageDescription: 'WoW Weekends',
  },
  {
    id: Date.now() + 1,
    imageLink: '../../../assets/images/fish-thumbnail.png',
    imageAlt: 'Fish',
    imageDescription: 'Coral Reef',
  },
  {
    id: Date.now() + 2,
    imageLink: '../../../assets/images/fish-thumbnail.png',
    imageAlt: 'Fish',
    imageDescription: 'Tropical Fish',
  },
  {
    id: Date.now() + 3,
    imageLink: '../../../assets/images/fish-thumbnail.png',
    imageAlt: 'Fish',
    imageDescription: 'Underwater World',
  },
  {
    id: Date.now() + 4,
    imageLink: '../../../assets/images/fish-thumbnail.png',
    imageAlt: 'Fish',
    imageDescription: 'Marine Life',
  },
  {
    id: Date.now() + 5,
    imageLink: '../../../assets/images/fish-thumbnail.png',
    imageAlt: 'Fish',
    imageDescription: 'Deep Sea Creatures',
  },
  {
    id: Date.now() + 6,
    imageLink: '../../../assets/images/fish-thumbnail.png',
    imageAlt: 'Fish',
    imageDescription: 'Exotic Species',
  },
  {
    id: Date.now() + 7,
    imageLink: '../../../assets/images/fish-thumbnail.png',
    imageAlt: 'Fish',
    imageDescription: 'Aquatic Wonders',
  },
  {
    id: Date.now() + 8,
    imageLink: '../../../assets/images/fish-thumbnail.png',
    imageAlt: 'Fish',
    imageDescription: 'Majestic Mollusks',
  },
  {
    id: Date.now() + 9,
    imageLink: '../../../assets/images/fish-thumbnail.png',
    imageAlt: 'Fish',
    imageDescription: 'Rivers and Streams',
  },
  {
    id: Date.now() + 10,
    imageLink: '../../../assets/images/fish-thumbnail.png',
    imageAlt: 'Fish',
    imageDescription: 'Freshwater Beauties',
  },
  {
    id: Date.now() + 11,
    imageLink: '../../../assets/images/fish-thumbnail.png',
    imageAlt: 'Fish',
    imageDescription: 'Saltwater Delights',
  },
];

export const BESTSELLERS = [
  {
    id: Date.now() + 1,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Chicken Curry Cut - Small Pieces',
    quantity: '500gms',
    discountedPrice: '179',
    price: '189',
    discount: '5%',
  },
  {
    id: Date.now() + 2,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Beef Steak',
    quantity: '500gms',
    discountedPrice: '199',
    price: '219',
    discount: '9%',
  },
  {
    id: Date.now() + 3,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Pork Chops',
    quantity: '500gms',
    discountedPrice: '169',
    price: '189',
    discount: '10%',
  },
  {
    id: Date.now() + 4,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Grilled Salmon',
    quantity: '250gms',
    discountedPrice: '299',
    price: '329',
    discount: '9%',
  },
  {
    id: Date.now() + 5,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'BBQ Ribs',
    quantity: '500gms',
    discountedPrice: '249',
    price: '269',
    discount: '7%',
  },
  {
    id: Date.now() + 6,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Fish Tacos',
    quantity: '4 pieces',
    discountedPrice: '149',
    price: '169',
    discount: '12%',
  },
  {
    id: Date.now() + 7,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Mushroom Risotto',
    quantity: '300gms',
    discountedPrice: '179',
    price: '199',
    discount: '10%',
  },
  {
    id: Date.now() + 8,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Shrimp Scampi',
    quantity: '400gms',
    discountedPrice: '249',
    price: '279',
    discount: '11%',
  },
  {
    id: Date.now() + 9,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Lemon Herb Chicken',
    quantity: '500gms',
    discountedPrice: '199',
    price: '219',
    discount: '9%',
  },
  {
    id: Date.now() + 10,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Pesto Pasta',
    quantity: '300gms',
    discountedPrice: '159',
    price: '179',
    discount: '11%',
  },
  {
    id: Date.now() + 11,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Teriyaki Salmon',
    quantity: '250gms',
    discountedPrice: '279',
    price: '299',
    discount: '6%',
  },
  {
    id: Date.now() + 12,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Stuffed Bell Peppers',
    quantity: '4 pieces',
    discountedPrice: '189',
    price: '209',
    discount: '9%',
  },
  {
    id: Date.now() + 13,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Sesame Beef Stir-Fry',
    quantity: '400gms',
    discountedPrice: '219',
    price: '239',
    discount: '8%',
  },
  {
    id: Date.now() + 14,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Caprese Salad',
    quantity: '250gms',
    discountedPrice: '149',
    price: '169',
    discount: '12%',
  },
  {
    id: Date.now() + 15,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Garlic Butter Shrimp',
    quantity: '400gms',
    discountedPrice: '249',
    price: '279',
    discount: '11%',
  },
  {
    id: Date.now() + 16,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Mongolian Beef',
    quantity: '400gms',
    discountedPrice: '229',
    price: '249',
    discount: '8%',
  },
  {
    id: Date.now() + 17,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Baked Ziti',
    quantity: '300gms',
    discountedPrice: '169',
    price: '189',
    discount: '10%',
  },
  {
    id: Date.now() + 18,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Lemon Garlic Butter Salmon',
    quantity: '250gms',
    discountedPrice: '299',
    price: '329',
    discount: '9%',
  },
  {
    id: Date.now() + 19,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Greek Salad',
    quantity: '300gms',
    discountedPrice: '159',
    price: '179',
    discount: '11%',
  },
  {
    id: Date.now() + 20,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Stuffed Chicken Breast',
    quantity: '500gms',
    discountedPrice: '219',
    price: '239',
    discount: '8%',
  },
  {
    id: Date.now() + 21,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Thai Red Curry',
    quantity: '400gms',
    discountedPrice: '249',
    price: '279',
    discount: '11%',
  },
  {
    id: Date.now() + 22,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Honey Garlic Chicken',
    quantity: '500gms',
    discountedPrice: '189',
    price: '209',
    discount: '9%',
  },
  {
    id: Date.now() + 23,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Penne Alfredo',
    quantity: '300gms',
    discountedPrice: '179',
    price: '199',
    discount: '10%',
  },
  {
    id: Date.now() + 24,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Orange Glazed Salmon',
    quantity: '250gms',
    discountedPrice: '299',
    price: '329',
    discount: '9%',
  },
  {
    id: Date.now() + 25,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Mediterranean Quinoa Salad',
    quantity: '300gms',
    discountedPrice: '159',
    price: '179',
    discount: '11%',
  },
  {
    id: Date.now() + 26,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Beef Stir-Fry',
    quantity: '400gms',
    discountedPrice: '219',
    price: '239',
    discount: '8%',
  },
  {
    id: Date.now() + 27,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Chicken Parmesan',
    quantity: '500gms',
    discountedPrice: '189',
    price: '209',
    discount: '9%',
  },
  {
    id: Date.now() + 28,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Vegetable Fried Rice',
    quantity: '300gms',
    discountedPrice: '159',
    price: '179',
    discount: '11%',
  },
  {
    id: Date.now() + 29,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Baked Salmon',
    quantity: '250gms',
    discountedPrice: '289',
    price: '319',
    discount: '9%',
  },
  {
    id: Date.now() + 30,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Shrimp Pasta',
    quantity: '400gms',
    discountedPrice: '249',
    price: '279',
    discount: '11%',
  },
  {
    id: Date.now() + 31,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Butter Chicken',
    quantity: '500gms',
    discountedPrice: '199',
    price: '219',
    discount: '9%',
  },
  {
    id: Date.now() + 32,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Cajun Shrimp Skillet',
    quantity: '400gms',
    discountedPrice: '229',
    price: '249',
    discount: '8%',
  },
  {
    id: Date.now() + 33,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Caesar Salad',
    quantity: '250gms',
    discountedPrice: '149',
    price: '169',
    discount: '12%',
  },
  {
    id: Date.now() + 34,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Beef and Broccoli',
    quantity: '400gms',
    discountedPrice: '239',
    price: '259',
    discount: '7%',
  },
  {
    id: Date.now() + 35,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Spinach and Feta Stuffed Chicken',
    quantity: '500gms',
    discountedPrice: '189',
    price: '209',
    discount: '9%',
  },
  {
    id: Date.now() + 36,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Chicken Fajitas',
    quantity: '500gms',
    discountedPrice: '199',
    price: '219',
    discount: '9%',
  },
  {
    id: Date.now() + 37,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Lemon Pepper Salmon',
    quantity: '250gms',
    discountedPrice: '289',
    price: '319',
    discount: '9%',
  },
  {
    id: Date.now() + 38,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Mushroom and Spinach Pasta',
    quantity: '300gms',
    discountedPrice: '169',
    price: '189',
    discount: '10%',
  },
  {
    id: Date.now() + 39,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Honey Garlic Glazed Salmon',
    quantity: '250gms',
    discountedPrice: '299',
    price: '329',
    discount: '9%',
  },
  {
    id: Date.now() + 40,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Mongolian Chicken',
    quantity: '500gms',
    discountedPrice: '199',
    price: '219',
    discount: '9%',
  },
  {
    id: Date.now() + 41,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Shrimp Tacos',
    quantity: '4 pieces',
    discountedPrice: '169',
    price: '189',
    discount: '10%',
  },
  {
    id: Date.now() + 42,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Greek Gyro',
    quantity: '1 piece',
    discountedPrice: '149',
    price: '169',
    discount: '12%',
  },
  {
    id: Date.now() + 43,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Steak Fajitas',
    quantity: '500gms',
    discountedPrice: '219',
    price: '239',
    discount: '8%',
  },
  {
    id: Date.now() + 44,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Caprese Chicken',
    quantity: '500gms',
    discountedPrice: '189',
    price: '209',
    discount: '9%',
  },
  {
    id: Date.now() + 45,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Vegetable Stir-Fry',
    quantity: '400gms',
    discountedPrice: '199',
    price: '219',
    discount: '9%',
  },
  {
    id: Date.now() + 46,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Grilled Shrimp Skewers',
    quantity: '400gms',
    discountedPrice: '229',
    price: '249',
    discount: '8%',
  },
  {
    id: Date.now() + 47,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Spinach Salad',
    quantity: '250gms',
    discountedPrice: '149',
    price: '169',
    discount: '12%',
  },
  {
    id: Date.now() + 48,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Beef and Mushroom Stir-Fry',
    quantity: '400gms',
    discountedPrice: '239',
    price: '259',
    discount: '7%',
  },
  {
    id: Date.now() + 49,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Stuffed Zucchini Boats',
    quantity: '4 pieces',
    discountedPrice: '179',
    price: '199',
    discount: '10%',
  },
  {
    id: Date.now() + 50,
    imageLink: '../../../assets/images/chicken-breast.webp',
    heading: 'Lemon Herb Grilled Chicken',
    quantity: '500gms',
    discountedPrice: '189',
    price: '209',
    discount: '9%',
  },
];

export const MENU = [
  {
    category: 'Spreads',
    items: [
      'Chunky Continental Chicken Spread',
      'Chunky Butter Chicken Spread',
      'Chunky Sweet Tamarind Chicken Spread',
      'Chunky Herby Tomato Chicken Spread',
      'Chunky Shawarma Chicken Spread',
      'Chunky Honey-Mustard Chicken Spread',
    ],
  },
  {
    category: 'Chicken',
    items: [
      'Chicken Curry Cut (Large - 8 to 10 Pieces)',
      'Chicken Breast - Boneless',
      'Chicken Drumstick - Skinless',
      'Tender Spring Chicken Curry Cut',
      'Chicken Leg (Whole) with Thigh',
      'Chicken Thigh (Boneless)',
    ],
  },
  {
    category: 'Mutton',
    items: [
      'Goat Boneless',
      'Goat Mince/Keema',
      'Premium Lamb Curry Cut',
      'Goat Shoulder - Curry Cut',
      'Lamb Boneless',
      'Goat Curry Cut (Shoulder Chaamp Puth - 11 to 14 pieces)',
    ],
  },
  {
    category: 'Fish & Seafood',
    items: [
      'Seer (Surmai) Steaks',
      'Freshwater Rohu Large - Bengali Cut (w/o Head)',
      'White Pomfret - (Whole and Cleaned)',
      'Indian Salmon/Rawas Steaks',
      'Basa Fillet - (Platinum Grade)',
      'Prawns Small (Whole)',
      'Freshwater Rohu - Bengali Cut (Without Head)',
      'Singara Steaks',
    ],
  },
  {
    category: 'Meat Masala',
    items: [
      'Asli Garam Masala',
      'Original Tandoori Chicken Masala',
      'Shandaar Butter Chicken Masala',
      'Khansama Biryani Masala',
      'Classic Meat Masala',
      'Chatpata Fish Fry Masala',
      'Dakshin Pepper Fry Masala',
    ],
  },
];

export const FISH_CATEGORY = [
  {
    id: Date.now() + 1,
    name: 'Parshe - Whole & Cleaned, No Tail',
    imageLink: '../../../assets/images/fish.webp',
    imgAlt: 'Fish',
    otherName: 'Also called Paarshe',
    qty: 450,
    pieces: 15,
    serving: 4,
    price: 599,
  },
  {
    id: Date.now() + 2,
    name: 'Hilsa - Bengali Style',
    imageLink: '../../../assets/images/fish.webp',
    imgAlt: 'Fish',
    otherName: 'Also called Ilish',
    qty: 500,
    pieces: 6,
    serving: 2,
    price: 1299,
  },
  {
    id: Date.now() + 3,
    name: 'Rohu - Bengali Mustard Curry',
    imageLink: '../../../assets/images/fish.webp',
    imgAlt: 'Fish',
    otherName: '',
    qty: 600,
    pieces: 5,
    serving: 3,
    price: 499,
  },
  {
    id: Date.now() + 4,
    name: 'Katla - Fried with Spices',
    imageLink: '../../../assets/images/fish.webp',
    imgAlt: 'Fish',
    otherName: '',
    qty: 700,
    pieces: 3,
    serving: 2,
    price: 699,
  },
  {
    id: Date.now() + 5,
    name: 'Pomfret - Tandoori Style',
    imageLink: '../../../assets/images/fish.webp',
    imgAlt: 'Fish',
    otherName: '',
    qty: 0,
    pieces: 4,
    serving: 2,
    price: 899,
  },
  {
    id: Date.now() + 6,
    name: 'Bhetki - Steamed with Lemon Sauce',
    imageLink: '../../../assets/images/fish.webp',
    imgAlt: 'Fish',
    otherName: '',
    qty: 0,
    pieces: 2,
    serving: 1,
    price: 599,
  },
  {
    id: Date.now() + 7,
    name: 'Pabda - Curry with Mustard Seeds',
    imageLink: '../../../assets/images/fish.webp',
    imgAlt: 'Fish',
    otherName: '',
    qty: 350,
    pieces: 8,
    serving: 3,
    price: 449,
  },
  {
    id: Date.now() + 8,
    name: 'Tilapia - Crispy Fried',
    imageLink: '../../../assets/images/fish.webp',
    imgAlt: 'Fish',
    otherName: '',
    qty: 500,
    pieces: 6,
    serving: 2,
    price: 399,
  },
  {
    id: Date.now() + 9,
    name: 'Singhara - Spicy Grilled',
    imageLink: '../../../assets/images/fish.webp',
    imgAlt: 'Fish',
    otherName: 'Also called Catfish',
    qty: 450,
    pieces: 10,
    serving: 3,
    price: 549,
  },
  {
    id: Date.now() + 10,
    name: 'Pangasius - Coconut Curry',
    imageLink: '../../../assets/images/fish.webp',
    imgAlt: 'Fish',
    otherName: '',
    qty: 600,
    pieces: 4,
    serving: 2,
    price: 699,
  },
];
